{% set version = "1.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mopa
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/SantanderMetGroup/mopa/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 48fb3957c2508ce1f418e250ef8260ef3382591e46e31b30ba6429cbd4efd593

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base <4.1
    - r-presenceabsence
    - r-abind
    - r-dismo
    - r-e1071
    - r-earth
    - r-gtools
    - r-lattice
    - r-randomforest
    - r-ranger
    - r-raster
    - r-rpart
    - r-sampling
    - r-sp
    - r-spam
    - r-spatstat <2
    - r-splancs
    - r-transformer
    - r-tree
  run:
    - r-base <4.1
    - r-presenceabsence
    - r-abind
    - r-dismo
    - r-e1071
    - r-earth
    - r-gtools
    - r-lattice
    - r-randomforest
    - r-ranger
    - r-raster
    - r-rpart
    - r-sampling
    - r-sp
    - r-spam
    - r-spatstat <2
    - r-splancs
    - r-transformer
    - r-tree

test:
  commands:
    - $R -e "library('mopa')"           # [not win]
    - "\"%R%\" -e \"library('mopa')\""  # [win]

about:
  home: https://github.com/SantanderMetGroup/mopa/wiki
  license: GPL-3.0-or-later
  summary: Transferable Species Distribution Modeling and Pseudo-absence data generation.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - cofinoa


# Package: mopa
# Depends: R (>= 3.4.0), raster, sp
# Imports: splancs, spam, spatstat, sampling, dismo, rpart, tree, e1071, earth, randomForest, PresenceAbsence, lattice, gtools, ranger, abind,
# Suggests: rJava (>= 0.5-0), caret (>= 6.0-76), loadeR (>= 1.0.9), downscaleR (>= 2.0-0), transformeR (>= 0.0.8)
# Type: Package
# Title: Species Distribution MOdeling with Pseudo-Absences
# Version: 1.0.0
# Date: 2017-05-02
# Authors@R: as.person(c( "Joaquin Bedia <bediaj@unican.es> [ctb]", "Maialen Iturbide <miturbide@ifca.unican.es> [aut, cre]", "Santander Meteorology Group <http://meteo.unican.es> [ctb]"))
# Description: Transferable Species Distribution Modeling and Pseudo-absence data generation.
# BugReports: https://github.com/SantanderMetGroup/mopa/issues
# URL: https://github.com/SantanderMetGroup/mopa/wiki
# License: file LICENSE
# LazyLoad: true
# RoxygenNote: 6.0.1
# Maintainer: Maialen Iturbide <miturbide@ifca.unican.es>
